# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - mongo
    env_file:
      - '.env'
    ports:
      - '8000:8000'
    command: npm run start
    volumes:
      - .:/app/
  mongo:
    image: mongo:4.4.0-bionic
    ports:
      - '27017:27017'
